In [2]:
import torch
from torch import nn

In [9]:
N = 10
A = nn.Embedding(N, 3)

In [10]:
print(A.weight)

Parameter containing:
tensor([[-0.7811, -1.2900, -0.1534],
        [ 0.0048,  0.5548, -1.0455],
        [-1.3004,  0.7248,  0.8710],
        [ 0.9565, -0.3854, -1.2529],
        [ 0.2312,  1.7182, -0.9151],
        [-1.3384, -1.5365,  0.3936],
        [-0.5668, -0.1275,  1.1321],
        [ 0.7598,  0.5736,  0.5043],
        [ 1.4795,  0.3038,  2.2709],
        [ 0.2191,  1.0318,  0.4833]], requires_grad=True)


In [11]:
full_range = torch.arange(N)
targ = 2
context_indices = full_range
k_ind = torch.argsort(torch.sum(torch.pow(A(context_indices) - A(torch.tensor(targ)), 2), dim = -1))

In [14]:
import string
vocabulary = {}
for index, letter in enumerate(string.ascii_lowercase[:N]):
    vocabulary[letter] = index

In [17]:
k_ind

tensor([2, 6, 9, 7, 5, 0, 1, 4, 8, 3])

In [16]:
for i in k_ind:
    word = list(vocabulary.keys())[i]
    print(word, vocabulary[word])

c 2
g 6
j 9
h 7
f 5
a 0
b 1
e 4
i 8
d 3


In [66]:
window_size = 2
idx = 0
N_max = 4

In [75]:
for idx in range(N_max):
    start = idx - window_size
    end = idx + window_size + 1
    full_range = torch.arange(start, end)
    print(full_range)
    negative_left_elements = (full_range < 0)
    negative_right_elements = (full_range >= N_max)
    full_range[negative_left_elements] = -full_range[negative_left_elements] + 2*idx
    full_range[negative_right_elements] -= (end - start - 1)
    print(full_range)

tensor([-2, -1,  0,  1,  2])
tensor([4, 5, 0, 1, 2])
tensor([-1,  0,  1,  2,  3])
tensor([5, 0, 1, 2, 3])
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 0])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 0, 1])


In [26]:
with open('myfile.txt', 'a') as file:
    file.write('index,word,window_size,embedding_size,word1,word2,word3,word4,word5,word6,word7,word8,word9,word10,word11,word12,word13,word14,word15,word16,word17,word18,word19,word20\n')

In [27]:
with open('myfile.txt', 'a') as file:
    file.write('0,1,1,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19\n')

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../train/result.csv')

In [3]:
data

word  window_size  embedding_size            word1  \
0          война            1              10         отвыкать   
1            мир            1              10      забавляться   
2         любовь            1              10            книга   
3   аристократия            1              10        объявлять   
4         судьба            1              10       порошковый   
5        героизм            1              10       василиевич   
6          семья            1              10           корпус   
7          честь            1              10              сан   
8         дружба            1              10     обмахиваться   
9      революция            1              10         засыхать   
10        Россия            1              10    успокоительно   
11      Наполеон            1              10       поселиться   
12          брак            1              10         коренник   
13        измена            1              10               эй   
14        жертва            1              10  удовлетвориться   
15           дуб            1              10        страстный   
16          небо            1              10      представить   
17          Пьер            1              10            винцо   
18       Безухов            1              10        вживаться   
19        Наташа            1              10        белолицый   
20        Ростов            1              10        равенство   
21        Андрей            1              10           щепоть   
22    Болконский            1              10         посланик   
23       Николай            1              10             ящик   
24         Марья            1              10     прослезиться   
25       Курагин            1              10              миг   
26        Москва            1              10          поверье   
27          поле            1              10    положительный   
28        имение            1              10       неизбежный   
29         война           21              10         угрожать   
30           мир           21              10           иголка   
31        любовь           21              10          лишение   
32  аристократия           21              10            комар   
33        судьба           21              10       отдуваться   
34       героизм           21              10             зима   
35         семья           21              10        поспевать   
36         честь           21              10          фурштат   
37        дружба           21              10           громко   
38     революция           21              10          приступ   
39        Россия           21              10   ниспровергнуть   
40      Наполеон           21              10        спереться   
41          брак           21              10           взбить   
42        измена           21              10            feind   
43        жертва           21              10      болезненный   
44           дуб           21              10        требовать   
45          небо           21              10         искатель   
46          Пьер           21              10       оглядеться   
47       Безухов           21              10       нацелиться   
48        Наташа           21              10           examen   
49        Ростов           21              10         donnerez   
50        Андрей           21              10         отломать   
51    Болконский           21              10            битва   
52       Николай           21              10              but   
53         Марья           21              10       приступить   
54       Курагин           21              10          вдыхать   
55        Москва           21              10              oни   
56          поле           21              10               mы   
57        имение           21              10          кирилыч   

              word2               word3            word4          word5  \
0      опровергнуть          невыгодный   

In [23]:
data.loc[0] = ['1', 1, 1] + ["Андрей" for i in range(20)]

In [25]:
data.to_csv("test.csv")